config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'profile', to: 'profile#index', as: 'profile'
  resources :forms, only: %i[ index show ]
  
  # Override default devise routes with routes to custom controllers
  Rails.application.routes.draw do
  get 'profile/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  resources :lessons, only: %i[ index ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'

  get '/engage_scraper', to: 'engage_scraper#scrape', as: 'scrape_engage'
  get '/engage_scraper/authorise', to: 'engage_scraper#authorise', as: 'authorise_scrape_engage'
end

app/views/shared/_alert_validation.html.erb
<!-- USE THIS PARTIAL INSIDE FORM IF YOU WANT TO USE SERVER SIDE VALIDATION -->
<% if resource.errors.present? %>
  <div class="alert alert-danger alert-dismissible show fade">
    <div class="alert-body">
      <button class="close" data-dismiss="alert"><span>&times;</span></button>
      <h5>Please correct the following items and try again:</h5>
      <ul class="pl-3">
        <% resource.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/shared/_card_dropdown.html.erb
<div class="dropdown">
  <a href="#" data-toggle="dropdown" class="btn btn-icon btn-secondary"><i class="fas fa-ellipsis-h"></i></a>
  <div class="dropdown-menu dropdown-menu-right">
    <%= yield %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="main-footer">
  <div class="footer-left">
    Copyright &copy; <%= Date.today.year %> <div class="bullet"></div>
  </div>
  <div class="footer-right">
    version 1.1
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg main-navbar">
  <form class="form-inline mr-auto">
    <ul class="navbar-nav mr-3">
      <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
      <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a></li>
    </ul>
    <div class="search-element">
      <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
      <button class="btn" type="submit"><i class="fas fa-search"></i></button>
      <div class="search-backdrop"></div>
      <div class="search-result">
        <!-- <div class="search-header">
          Histories
        </div>
        <div class="search-item">
          <a href="#">How to hack NASA using CSS</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-item">
          <a href="#">Kodinger.com</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-item">
          <a href="#">#Stisla</a>
          <a href="#" class="search-close"><i class="fas fa-times"></i></a>
        </div>
        <div class="search-header">
          Result
        </div>
        <div class="search-item">
          <a href="#">
            <%= image_tag('products/product-3-50.png', width: 30, class: 'mr-3 rounded') %>
            oPhone S9 Limited Edition
          </a>
        </div>
        <div class="search-item">
          <a href="#">
            <%= image_tag('products/product-2-50.png', width: 30, class: 'mr-3 rounded') %>
            Drone X2 New Gen-7
          </a>
        </div>
        <div class="search-item">
          <a href="#">
            <%= image_tag('products/product-1-50.png', width: 30, class: 'mr-3 rounded') %>
            Headphone Blitz
          </a>
        </div>
        <div class="search-header">
          Projects
        </div>
        <div class="search-item">
          <a href="#">
            <div class="search-icon bg-danger text-white mr-3">
              <i class="fas fa-code"></i>
            </div>
            Stisla Admin Template
          </a>
        </div>
        <div class="search-item">
          <a href="#">
            <div class="search-icon bg-primary text-white mr-3">
              <i class="fas fa-laptop"></i>
            </div>
            Create a new Homepage Design
          </a>
        </div> -->
        <div class="search-item">
          <a href="javascript:;">
            <div class="search-icon bg-primary text-white mr-3">
              <i class="fas fa-search"></i>
            </div>
            The search feature isn't ready yet.
          </a>
        </div> 

      </div>
    </div>
  </form>
  <ul class="navbar-nav navbar-right">
    <%# Messages %>
    <!-- <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
      <div class="dropdown-menu dropdown-list dropdown-menu-right">
        <div class="dropdown-header">Messages
          <div class="float-right">
            <a href="#">Mark All As Read</a>
          </div>
        </div>
        <div class="dropdown-list-content dropdown-list-message">
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <%= image_tag('avatar/avatar-1.png', class: 'rounded-circle') %>
              <div class="is-online"></div>
            </div>
            <div class="dropdown-item-desc">
              <b>Kusnaedi</b>
              <p>Hello, Bro!</p>
              <div class="time">10 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <%= image_tag('avatar/avatar-2.png', class: 'rounded-circle') %>
            </div>
            <div class="dropdown-item-desc">
              <b>Dedik Sugiharto</b>
              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
              <div class="time">12 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-avatar">
              <%= image_tag('avatar/avatar-3.png', class: 'rounded-circle') %>
              <div class="is-online"></div>
            </div>
            <div class="dropdown-item-desc">
              <b>Agung Ardiansyah</b>
              <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              <div class="time">12 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-avatar">
              <%= image_tag('avatar/avatar-4.png', class: 'rounded-circle') %>
            </div>
            <div class="dropdown-item-desc">
              <b>Ardian Rahardiansyah</b>
              <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
              <div class="time">16 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-avatar">
              <%= image_tag('avatar/avatar-4.png', class: 'rounded-circle') %>
            </div>
            <div class="dropdown-item-desc">
              <b>Alfa Zulkarnain</b>
              <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
              <div class="time">Yesterday</div>
            </div>
          </a>
        </div>
        <div class="dropdown-footer text-center">
          <a href="#">View All <i class="fas fa-chevron-right"></i></a>
        </div>
      </div>
    </li> -->


    <%# Notifications %>
    <!-- <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown" class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
      <div class="dropdown-menu dropdown-list dropdown-menu-right">
        <div class="dropdown-header">Notifications
          <div class="float-right">
            <a href="#">Mark All As Read</a>
          </div>
        </div>
        <div class="dropdown-list-content dropdown-list-icons">
          <a href="#" class="dropdown-item dropdown-item-unread">
            <div class="dropdown-item-icon bg-primary text-white">
              <i class="fas fa-code"></i>
            </div>
            <div class="dropdown-item-desc">
              Template update is available now!
              <div class="time text-primary">2 Min Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-icon bg-info text-white">
              <i class="far fa-user"></i>
            </div>
            <div class="dropdown-item-desc">
              <b>You</b> and <b>Dedik Sugiharto</b> are now friends
              <div class="time">10 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-icon bg-success text-white">
              <i class="fas fa-check"></i>
            </div>
            <div class="dropdown-item-desc">
              <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
              <div class="time">12 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-icon bg-danger text-white">
              <i class="fas fa-exclamation-triangle"></i>
            </div>
            <div class="dropdown-item-desc">
              Low disk space. Let's clean it!
              <div class="time">17 Hours Ago</div>
            </div>
          </a>
          <a href="#" class="dropdown-item">
            <div class="dropdown-item-icon bg-info text-white">
              <i class="fas fa-bell"></i>
            </div>
            <div class="dropdown-item-desc">
              Welcome to Stisla template!
              <div class="time">Yesterday</div>
            </div>
          </a>
        </div>
        <div class="dropdown-footer text-center">
          <a href="#">View All <i class="fas fa-chevron-right"></i></a>
        </div>
      </div>
    </li> -->
    
    <%# Profile %>
    <% if user_signed_in? %>
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
        <%= image_tag('avatar/avatar-1.png', class: 'rounded-circle mr-1') %>
        <div class="d-sm-none d-lg-inline-block"><%= current_user.full_name if user_signed_in? %></div></a>
        <div class="dropdown-menu dropdown-menu-right">
          <div class="dropdown-title">Logged in <%= distance_of_time_in_words(DateTime.now, current_user.current_sign_in_at) %> ago</div>
          <%= link_to profile_path, class: 'dropdown-item has-icon' do %>
            <i class="far fa-user"></i> Profile
          <% end %>
          <!-- <a href="features-activities.html" class="dropdown-item has-icon">
            <i class="fas fa-bolt"></i> Activities
          </a>
          <a href="features-settings.html" class="dropdown-item has-icon">
            <i class="fas fa-cog"></i> Settings
          </a> -->
          <div class="dropdown-divider"></div>
          <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item has-icon text-danger' do %>
            <i class="fas fa-sign-out-alt"></i> Log out
          <% end %>
        </div>
      </li>
    <% else %>
      <li class="dropdown"><a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
      <%= link_to "Sign up", user_registration_path, class: 'btn btn-light' %>
      </li>
    <% end %>
  </ul>
</nav>

app/views/shared/_sidebar.html.erb
<div class="main-sidebar sidebar-style-2">
  <aside id="sidebar-wrapper">
    <div class="sidebar-brand">
      <%= link_to 'Engage Scraper', root_path  %>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
      <%= link_to 'ES', root_path %>
    </div>
    <ul class="sidebar-menu" data-controller="sidebar">
      <li class="<%= active_nav_item('home', 'index') %>">
        <%= link_to root_path, class: "nav-link" do %>
          <i class="fas fa-fire"></i> <span>Dashboard</span>
        <% end %>
      </li>

      <li class="<%= active_nav_item('lessons', 'index') %>">
        <%= link_to lessons_path, class: "nav-link" do %>
          <i class="fas fa-chalkboard-teacher"></i> <span>Timetable</span>
        <% end %>
      </li>

      <li class="<%= active_nav_item('forms', 'show') %>">
        <%= link_to current_user.form, class: "nav-link" do %>
          <i class="fas fa-users"></i> <span>Form</span>
        <% end %>
      </li>
      <!--
      <li class="menu-header">Controllers</li>
      <%= render 'shared/sidebar_dropdown', title: 'Resources', icon: 'fas fa-file-alt' do %>
      
        <li class="<#= active_nav_item('customers', crud_actions) #>">
          <#= link_to 'Customers', customers_path, class: 'nav-link' #>
        </li>
      -->
      <% end %>
    </ul>

    <div class="mt-4 mb-4 p-3 hide-sidebar-mini">
      <%= link_to authorise_scrape_engage_path, class: "btn btn-primary btn-lg btn-block btn-icon-split" do %>
        <i class="fas fa-sync"></i> <span>Sync with Engage</span>
      <% end %>
    </div>

  </aside>
</div>

app/views/shared/_sidebar_dropdown.html.erb
<li class="nav-item dropdown">
  <a href="#" class="nav-link has-dropdown" data-toggle="dropdown">
    <i class="<%= icon %>"></i> <span><%= title %></span>
  </a>
  <ul class="dropdown-menu">
    <%= yield %>
  </ul>
</li>

app/views/shared/_toastr.html.erb
<% flash.each do |type, msg| %>
  <% if msg.present? && msg.is_a?(String) %>
    <div data-controller="toastr" data-toastr-type="<%= type %>" data-toastr-message="<%= msg %>"></div>
  <% end %>
<% end %>