config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'profile', to: 'profile#index', as: 'profile'
  resources :forms, only: %i[ index show ]
  
  # Override default devise routes with routes to custom controllers
  Rails.application.routes.draw do
  get 'profile/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  resources :lessons, only: %i[ index ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'

  get '/engage_scraper', to: 'engage_scraper#scrape', as: 'scrape_engage'
  get '/engage_scraper/authorise', to: 'engage_scraper#authorise', as: 'authorise_scrape_engage'
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user, optional: true
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: %i[ show edit update destroy ]

  def index
    if params[:teacher].present?
      @lessons = Lesson.where({ user: current_user, teacher: params[:teacher] }).reverse_chronologically

      respond_to do |format|
        format.any(:html, :json) { @lessons }
        format.csv { render csv: @lessons }
      end
    elsif params[:room].present?
      @lessons = Lesson.where({ user: current_user, room: params[:room] }).reverse_chronologically

      respond_to do |format|
        format.any(:html, :json) { @lessons }
        format.csv { render csv: @lessons }
      end
    else
      @search = Lesson.where({ user: current_user }).reverse_chronologically.ransack(params[:q])

      respond_to do |format|
        format.any(:html, :json) { @lessons = set_page_and_extract_portion_from @search.result }
        format.csv { render csv: @search.result }
      end
    end
  end

  # def show
  #   fresh_when etag: @lesson
  # end

  # def new
  #   @lesson = Lesson.new
  # end

  # def edit
  # end

  # def create
  #   @lesson = Lesson.new(lesson_params)
  #   @lesson.save!

  #   respond_to do |format|
  #     format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
  #     format.json { render :show, status: :created }
  #   end
  # end

  # def update
  #   @lesson.update!(lesson_params)
  #   respond_to do |format|
  #     format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
  #     format.json { render :show }
  #   end
  # end

  # def destroy
  #   @lesson.destroy
  #   respond_to do |format|
  #     format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    def lesson_params
      params.require(:lesson).permit(:name, :weekday, :start_time, :end_time, :teacher, :room)
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: lesson, data: { controller: 'validation' }) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :weekday %>
    <%= form.text_field :weekday, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :start_time %>
    <%= form.text_field :start_time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :end_time %>
    <%= form.text_field :end_time, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :teacher %>
    <%= form.text_field :teacher, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :room %>
    <%= form.text_field :room, class: 'form-control' %>
  </div>
  <div class="card-footer pl-0">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Lessons</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Lessons', lessons_path %></div>
      <div class="breadcrumb-item">Editing Lesson</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Editing Lesson</h4>
      </div>
      <div class="card-body">
        <%= render 'form', lesson: @lesson %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-eye', 'Show'), @lesson, class: 'btn btn-icon icon-left btn-info' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), lessons_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Editing Lesson') %>

app/views/lessons/index.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Timetable</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item">Timetable</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>
          <% if params[:teacher].present? %>
            List of classes taught by <%= params[:teacher] %> (<%= (@lessons.size.to_f/Lesson.all.size * 100).round %>%)
          <% elsif params[:room].present? %>
            List of classes that take place in <%= params[:room] %> (<%= (@lessons.size.to_f/Lesson.all.size * 100).round %>%)
          <% else %>
            List of classes
          <% end %>
        </h4>
        <div class="card-header-action">
        <%= link_to icon('fas fa-print', ' Print Page'), 'javascript:window.print()', class: 'btn btn-primary has-icon' %>
        </div>
      </div>
      <div class="card-body">
        <!--
        <#= search_form_for @search, remote: true, data: { controller: 'turbolinks-form' }, html: { class: 'form-row' } do |f| #>
          <div class="form-group col-sm-10">
            <#= f.text_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' #>
          </div>
          <div class="form-group col-sm-2 text-right">
            <#= f.button icon('fas fa-search', 'Search'), name: nil, class: 'btn btn-icon icon-left btn-primary' #>
          </div>
        <# end #>
        -->
        <!--
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th><%# sort_link_turbo(@search, :name) %></th>
                <th><%# sort_link_turbo(@search, :weekday) %></th>
                <th><%# sort_link_turbo(@search, :start_time) %></th>
                <th><%# sort_link_turbo(@search, :end_time) %></th>
                <th><%# sort_link_turbo(@search, :teacher) %></th>
                <th><%# sort_link_turbo(@search, :room) %></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody data-target="infinite-page.container">
              <%# @lessons.each do |lesson| %>
                <tr data-target="infinite-page.item">
                  <td><%# lesson.name %></td>
                  <td><%# Date::DAYNAMES[lesson.weekday.to_i] %></td>
                  <td><%# lesson.start_time %></td>
                  <td><%# lesson.end_time %></td>
                  <td><%# lesson.teacher %></td>
                  <td><%# lesson.room %></td>
                  <td>
                    <%# link_to icon('fas fa-eye'), lesson, title: 'Show it', class: 'btn btn-icon btn-sm btn-info mr-1' %>
                    <%# link_to icon('fas fa-edit'), edit_lesson_path(lesson), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' %>
                    <%# link_to icon('fas fa-trash'), lesson, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <%# end %>
            </tbody>
          </table>
          <%# link_to 'Next page', lessons_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div> 
        -->

        <div id="lesson-list" class="row">
          <% 1.upto 5 do |weekday| %>
            <div class="col-12 col-sm-6 col-md-6 col-lg-6 col-xl-4 pb-4">
              <div class="lesson-card alert h-100 <%= Date.today.wday == weekday ? 'alert-primary' : 'alert-secondary' %>">
                <div class="alert-title d-flex w-100 mb-2 justify-content-between">
                  <%= Date::DAYNAMES[weekday] %>
                  <% if Date.today.wday == weekday %>
                    <span class="badge badge-danger">Today</span>
                  <% end %>
                </div>
                
                <% if @lessons.where(weekday: weekday.to_s).any? # check whether there are lessons in that day %>

                  <ul class="list-group">

                    <% @lessons.where(weekday: weekday.to_s).reverse.each do |lesson| %>
                      
                      <li class="list-group-item list-group-item-action flex-column align-items-start <%= Time.now.strftime("%H:%M") > lesson.start_time && Time.now.strftime("%H:%M") < lesson.end_time && Date.today.wday == lesson.weekday.to_i ? 'list-group-item-danger' : 'list-group-item-light' %>">
                        <div class="d-flex w-100 justify-content-between">
                          <h6 class="mb-1"><%= lesson.name %></h6>
                          <%= link_to icon('fas fa-door-open mr-1', lesson.room), 
                            lessons_path(room: lesson.room), 
                            class: 'badge badge-info d-flex align-items-center',
                            'data-toggle' => 'tooltip',
                            'data-placement' => 'top',
                            'data-original-title' =>  case lesson.room[0] when 'A'
                                                        '6ᵗʰ form'
                                                      when 'S'
                                                        'Senior'
                                                      when 'J'
                                                        'Junior'
                                                      when 'N'
                                                        'Avenor Arena'
                                                      end
                          %>
                          
                        </div>
                        <p>
                          <i class="fas fa-clock fa-fw mr-1"></i>
                          <%= lesson.start_time %> – <%= lesson.end_time %>
                        </p>
                        <p>
                          <i class="fas fa-chalkboard-teacher fa-fw mr-1"></i>
                          <%= link_to lesson.teacher, lessons_path(teacher: lesson.teacher), class: "text-primary" %>
                        </p>
                      </li>

                    <% end %>

                  </ul>

                <% else # If there are no lessons in that day, show empty state %>
                  <div class="empty-state" data-height="300" style="height: 300px;">
                    <div class="empty-state-icon">
                      <i class="fas fa-question"></i>
                    </div>
                    <h2>There are no classes to show</h2>
                    <a href="javascript:;" 
                      onclick="window.Swal.fire({
                        icon: 'question',
                        text: 'Your information may have not been imported or processed correctly. Please press „Sync with Engage” in the sidebar to sync your data with Engage!',
                      })"
                      class="mt-4 bb"
                    >
                      Need Help?
                    </a>
                  </div>
                <% end %>

              </div>
            </div>
          <% end %>
        </div>

      </div>
    </div>
  </div>
</section>

<% content_for(:page_title, 'List of Lessons') %>

app/views/lessons/new.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Lessons</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Lessons', lessons_path %></div>
      <div class="breadcrumb-item">New Lesson</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>New Lesson</h4>
      </div>
      <div class="card-body">
        <%= render 'form', lesson: @lesson %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), lessons_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'New Lesson') %>

app/views/lessons/scrape.html.erb
<h1>Scraper</h1>
<p><%= @response %></p>

app/views/lessons/show.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Lessons</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Lessons', lessons_path %></div>
      <div class="breadcrumb-item">Show Lesson</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Show Lesson</h4>
      </div>
      <div class="card-body">
        <dl class="row">
          <dt class="col-sm-3">Name:</dt>
          <dd class="col-sm-9"><%= @lesson.name %></dd>
          <dt class="col-sm-3">Weekday:</dt>
          <dd class="col-sm-9"><%= @lesson.weekday %></dd>
          <dt class="col-sm-3">Start time:</dt>
          <dd class="col-sm-9"><%= @lesson.start_time %></dd>
          <dt class="col-sm-3">End time:</dt>
          <dd class="col-sm-9"><%= @lesson.end_time %></dd>
          <dt class="col-sm-3">Teacher:</dt>
          <dd class="col-sm-9"><%= @lesson.teacher %></dd>
          <dt class="col-sm-3">Room:</dt>
          <dd class="col-sm-9"><%= @lesson.room %></dd>
        </dl>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-edit', 'Edit'), edit_lesson_path(@lesson), class: 'btn btn btn-icon icon-left btn-warning' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), lessons_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Show Lesson') %>