config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'profile', to: 'profile#index', as: 'profile'
  resources :forms, only: %i[ index show ]
  
  # Override default devise routes with routes to custom controllers
  Rails.application.routes.draw do
  get 'profile/index'
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }
  end

  resources :lessons, only: %i[ index ]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'

  get '/engage_scraper', to: 'engage_scraper#scrape', as: 'scrape_engage'
  get '/engage_scraper/authorise', to: 'engage_scraper#authorise', as: 'authorise_scrape_engage'
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
  before_action :authenticate_user!
  
  before_action :set_form, only: %i[ show edit update destroy ]

  def index
    @search = Form.reverse_chronologically.ransack(params[:q])

    respond_to do |format|
      format.any(:html, :json) { @forms = set_page_and_extract_portion_from @search.result }
      format.csv { render csv: @search.result }
    end
  end

  def show
    fresh_when etag: @form
  end

  def new
    @form = Form.new
  end

  def edit
  end

  def create
    @form = Form.new(form_params)
    @form.save!

    respond_to do |format|
      format.html { redirect_to @form, notice: 'Form was successfully created.' }
      format.json { render :show, status: :created }
    end
  end

  def update
    @form.update!(form_params)
    respond_to do |format|
      format.html { redirect_to @form, notice: 'Form was successfully updated.' }
      format.json { render :show }
    end
  end

  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to forms_url, notice: 'Form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_form
      @form = Form.find(params[:id])
    end

    def form_params
      params.require(:form).permit(:name, :form_tutor)
    end
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/views/forms/_form.html.erb
<%= form_with(model: form, data: { controller: 'validation' }) do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= form.label :form_tutor %>
    <%= form.text_field :form_tutor, class: 'form-control' %>
  </div>
  <div class="card-footer pl-0">
    <%= form.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/forms/edit.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Forms</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Forms', forms_path %></div>
      <div class="breadcrumb-item">Editing Form</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>Editing Form</h4>
      </div>
      <div class="card-body">
        <%= render 'form', form: @form %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-eye', 'Show'), @form, class: 'btn btn-icon icon-left btn-info' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), forms_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Editing Form') %>

app/views/forms/index.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Forms</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item">List of Forms</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>List of Forms</h4>
        <div class="card-header-action">
          <%# link_to icon('fas fa-plus', 'New Form'), new_form_path, class: 'btn btn-icon icon-left btn-primary' %>
          <%# render 'shared/card_dropdown' do %>
            <%# link_to icon('fas fa-download', 'Export Data'), forms_path(format: :csv, q: request.params[:q]), class: 'dropdown-item has-icon' %>
            <%# link_to icon('fas fa-print', 'Print Page'), 'javascript:window.print()', class: 'dropdown-item has-icon' %>
          <%# end %>
        </div>
      </div>
      <div class="card-body" data-controller="infinite-page">
        <!--
        <#= search_form_for @search, remote: true, data: { controller: 'turbolinks-form' }, html: { class: 'form-row' } do |f| #>
          <div class="form-group col-sm-10">
            <#= f.text_field :name_cont, class: 'form-control m-input m-input--solid', placeholder: 'Name' #>
          </div>
          <div class="form-group col-sm-2 text-right">
            <#= f.button icon('fas fa-search', 'Search'), name: nil, class: 'btn btn-icon icon-left btn-primary' #>
          </div>
        <# end #>
        -->
        <div class="table-responsive">
          <table class="table table-striped table-md">
            <thead>
              <tr>
                <th><%= sort_link_turbo(@search, :name) %></th>
                <th><%= sort_link_turbo(@search, :form_tutor) %></th>
                <th><%= sort_link_turbo(@search, :students) %></th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody data-target="infinite-page.container">
              <% @forms.each do |form| %>
                <tr data-target="infinite-page.item">
                  <td><%= form.name %></td>
                  <td><%= form.form_tutor %></td>
                  <td><%= form.users.size %></td>
                  <td>
                    <%= link_to icon('fas fa-eye'), form, title: 'Show it', class: 'btn btn-icon btn-sm btn-info mr-1' %>
                    <%# link_to icon('fas fa-edit'), edit_form_path(form), title: 'Edit it', class: 'btn btn-icon btn-sm btn-warning mr-1' %>
                    <%# link_to icon('fas fa-trash'), form, title: 'Destroy it', class: 'btn btn-icon btn-sm btn-danger', method: :delete, data: { confirm: 'Are you sure?', remote: true } %>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to 'Next page', forms_path(page: @page.next_number, q: request.params[:q]), data: { target: 'infinite-page.more' } unless @page.last? %>
        </div>
      </div>
    </div>
  </div>
</section>

<% content_for(:page_title, 'List of Forms') %>

app/views/forms/new.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Forms</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Forms', forms_path %></div>
      <div class="breadcrumb-item">New Form</div>
    </div>
  </div>
  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4>New Form</h4>
      </div>
      <div class="card-body">
        <%= render 'form', form: @form %>
      </div>
    </div>
  </div>
</section>

<%= link_to icon('fas fa-arrow-left', 'Back'), forms_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'New Form') %>

app/views/forms/show.html.erb
<section class="section">
  <div class="section-header d-mobile-none">
    <h1>Forms</h1>
    <div class="section-header-breadcrumb">
      <div class="breadcrumb-item"><%= link_to 'Dashboard', root_path %></div>
      <div class="breadcrumb-item"><%= link_to 'Forms', forms_path %></div>
      <div class="breadcrumb-item">Show Form</div>
    </div>
  </div>

  <div class="section-body">
    <div class="card">
      <div class="card-header">
        <h4><%= @form.name %></h4>
      </div>
      <div class="card-body">
        <h6>Form tutor</h6>
        <ul class="list-group mb-4">
          <li class="list-group-item"><%= @form.form_tutor %></li>
        </ul>
        <h6>Students</h6>
        <% if @form.users.any? %>
          <ul class="list-group">
            <% @form.users.each do |u| %>
              <li class="list-group-item"><%= u.full_name %></li>
            <% end %>
          </ul>
        <% else %>
          <p>There are no students in this form.</p>
        <% end %>
      </div>
    </div>
  </div>
</section>

<%# link_to icon('fas fa-edit', 'Edit'), edit_form_path(@form), class: 'btn btn btn-icon icon-left btn-warning' %>
<%= link_to icon('fas fa-arrow-left', 'Back'), forms_path, class: 'btn btn-icon icon-left btn-secondary d-mobile-none' %>

<% content_for(:page_title, 'Show Form') %>